name: Validate code

on:
    pull_request:

permissions:
    contents: read

concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Nix
              uses: nixbuild/nix-quick-install-action@v30
            - name: Install packages
              run: nix --download-buffer-size 500000000 develop --command bash -c 'just install'
            - name: Lint
              run: nix develop --command bash -c 'just lint'
            - name: Test
              run: nix develop --command bash -c 'just test'
            - name: Build
              run: nix develop --command bash -c 'just build'
