name: Validate code

on:
    pull_request:

permissions:
    contents: read

concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Lint
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Nix
              uses: cachix/install-nix-action@v25
            - name: Run inside Nix dev shell
              run: nix develop --command bash -c 'npm install && just lint'
