name: Validate code

on:
    pull_request:

permissions:
    contents: read

concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Nix
              uses: nixbuild/nix-quick-install-action@v30
            - name: Install packages
              run: nix develop --command bash -c 'just install'
            - uses: actions/cache@v4
              with:
                  path: |
                      ${{ github.workspace }}/.next/cache
                  # Generate a new cache whenever packages or source files change.
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
                  # If source files changed but packages didn't, rebuild from a prior cache.
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            - name: Lint
              run: nix develop --command bash -c 'just lint'
            - name: Test
              run: nix develop --command bash -c 'just test'
            - name: Build
              run: nix develop --command bash -c 'just build'
