name: Validate code

on:
    pull_request:

permissions:
    contents: read

concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node.js and npm
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            - name: Install Nix
              uses: nixbuild/nix-quick-install-action@v30
            - name: Build in nix shell
              run: nix develop --command just
